### ISSUE TITLE
Lease POST metadata form format

### ISSUE THREAD

**Issue by chakrabortysaptarshi** [DilipKunderu/SEfa17#17]
Lease meta data form data field name and values - 

| Field Name | Value | datatype |
|-----------------|:-------:|-------------:|
avatar|av-image|file
search-id|id|hex
rent|rent-value|number
lat|lat-value|number
lon|lon-value|number
start-date|start-date|md-date
end-date|end-date|md-date

**Comment by DilipKunderu** [comment]
Can you rewrite the requirement in a JSON structure with field name as the key and the datatype as the value ?

**Comment by DilipKunderu** [comment]
Done by me. Correct the datatypes if they are wrong

**Comment by DilipKunderu** [comment]
field | type
--- | ---
rent | textbox
startdate | datepicker
enddate | datepicker 

map on the right

Images uploader area
