### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by DilipKunderu** [DilipKunderu/SEfa17#34]
Heroku
/
AWS/
whatever we can

**Comment by DilipKunderu** [comment]
We can run back-end on one laptop and front end on another laptop so no need to deploy anywhere. But he said that he would view deployment in a positive light

**Comment by chakrabortysaptarshi** [comment]
The back-end server will be running on my laptop, and front-end can be rendered from any machine using my laptop's ip address.
